apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: form-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Kafka broker connection setting
    - name: brokers
      value:
    - name: authRequired
      value: "false"
    - name: maxMessageBytes
      value: 1024