# port 端口
port: :40001

#  -------------------- log --------------------
# comply with zap log specification
log:
  level: -1
  development: false
  sampling:
    initial: 100
    thereafter: 100
  outputPath:
    - stderr
  errorOutputPath:
    - stderr

internalNet:
  timeout: 20
  maxIdleConns: 10

# --------------------- endpoint -------------
endpoint:
  poly: "http://poly.alpha"
  form: "http://localhost:80"
  formInner: "http://localhost:8080"
  search: "http://search.inner"

# --------------------- transport -----------------
transport:
  timeout: 20s
  keepAlive: 20s
  maxIdleConns: 10
  idleConnTimeout: 20s
  tlsHandshakeTimeout: 10s
  expectContinueTimeout: 1s



# -------------------- redis --------------------
redis:
  addrs:
    - 192.168.201.14:6379
    - 192.168.201.15:6379
    - 192.168.201.16:6379
  username:
  password: